name: CI tests and analysis

on: 
  push:
    branches: 
      - main
      - development
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Configure git
      run: git config --global advice.detachedHead false
      
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
      
    - name: Run PlatformIO unit tests
      run: platformio test -vvv -e native
  
  analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Configure git
      run: git config --global advice.detachedHead false
      
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Code static analysis
      run: pio check --skip-packages
